### ISSUE TITLE
Could not compile metadata Error

### ISSUE THREAD

**Issue by dlively1** [joeferraro/MavensMate-Atom#212]
Recently switched over to Atom MavensMate and ran into an issue trying to compile.

Originally it was just hanging on the compiling process and never updating the UI. I enabled the developer tools and see that it was returning the following:

```
Object {result: "Could not compile metadata", error: undefined, stack: undefined, promiseId: "336e1610-1514-11e5-a58d-e78f7e379093"}

COMMAND RESULT PARSER --> CompileMetadataParser
/Users/X/.atom/packages/MavensMate-Atom/lib/panel/parsers.coffee:532 parser is: 
/Users/X/.atom/packages/MavensMate-Atom/lib/panel/parsers.coffee:533 function CompileParser() {
      return CompileParser.__super__.constructor.apply(this, arguments);
    }
/Users/X/.atom/packages/MavensMate-Atom/lib/panel/parsers.coffee:155 result!
/Users/X/.atom/packages/MavensMate-Atom/lib/panel/parsers.coffee:156 Could not compile metadata
```

I then switched to not using the tooling API  and now get the following error which now updates in the UI 

```
{
  "result": "Could not compile metadata",
  "error": "INVALID_OPERATION: No zip file content passed in",
  "stack": "sf:INVALID_OPERATION: INVALID_OPERATION: No zip file content passed in\n  at [object Object].HttpApi.getError (/Users/X/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/lib/http-api.js:240:13)\n  at /Users/X/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/lib/http-api.js:85:22\n  at /Users/X/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/promise/lib/core.js:33:15\n  at flush (/Users/X/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/promise/node_modules/asap/asap.js:27:13)\n  at process._tickCallback (node.js:357:13)\n",
  "promiseId": "3918d9c0-1513-11e5-b9d1-45f7969b398c"
}
```
I've tried cleaning the project and refreshing metadata which all work successfully but still getting the above errors.

Atom Version: 0.209.0
MavensMate Version: 0.38.6
MavensMate Atom Version: 0.0.24

**Comment by adtennant** [comment]
+1, it also occurs when trying to create new metadata, e.g. an Apex class.

OSX
Atom: 0.210.0
MavensMate Atom: 0.0.24 (and 0.0.23, I downgraded to check if it fixed the issue)

**Comment by lydonb** [comment]
+1 

OSX: 10.9.5
Atom: 1.0.0
MM-Atom: 0.0.24

I even tried to fully uninstall atom like this: https://discuss.atom.io/t/how-to-completely-uninstall-atom-for-mac/9084/6

And still have the same issue.

**Comment by robertpeacock22** [comment]
+1

Same stack trace as @dlively1.

```javascript
{
  "result": "Could not compile metadata",
  "error": "INVALID_OPERATION: No zip file content passed in",
  "stack": "sf:INVALID_OPERATION: INVALID_OPERATION: No zip file content passed in\n  at [object Object].HttpApi.getError (/Users/robert/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/lib/http-api.js:240:13)\n  at /Users/robert/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/lib/http-api.js:85:22\n  at /Users/robert/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/promise/lib/core.js:33:15\n  at flush (/Users/robert/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/promise/node_modules/asap/asap.js:27:13)\n  at process._tickCallback (node.js:357:13)\n",
  "promiseId": "73f926d0-1eaa-11e5-8ca4-310bf7e12d84"
}
```

**Comment by lydonb** [comment]
I tried to track this down through the source, and it looks like the POST to /services/data/vXX/tooling/sobjects/MetadataContainer is failing with a 404.

Stringified Request:
`{"method":"POST","url":"https://csX.salesforce.com/services/data/v34/tooling/sobjects/MetadataContainer","body":"{\"name\":\"xnGcstJhEIGVh5zi1OwTDK7pAKAWBtKk\"}","headers":{"Content-Type":"application/json","Authorization":"Bearer <A long char string here>"}}`

Stringified Response (this is the response when I tried to change to API v32, but v34 is the same):
`{"statusCode":404,"body":"[{\"errorCode\":\"NOT_FOUND\",\"message\":\"The requested resource does not exist\"}]","headers":{"date":"Tue, 30 Jun 2015 01:16:09 GMT","set-cookie":["BrowserId=<long string>;Path=/;Domain=.salesforce.com;Expires=Sat, 29-Aug-2015 01:16:10 GMT"],"expires":"Thu, 01 Jan 1970 00:00:00 GMT","content-type":"application/json;charset=UTF-8","transfer-encoding":"chunked","connection":"close"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"cs8.salesforce.com","port":443,"hostname":"cs8.salesforce.com","hash":null,"search":null,"query":null,"pathname":"/services/data/v32/tooling/sobjects/MetadataContainer","path":"/services/data/v32/tooling/sobjects/MetadataContainer","href":"https://cs8.salesforce.com/services/data/v32/tooling/sobjects/MetadataContainer"},"method":"POST","headers":{"Content-Type":"application/json","Authorization":"Bearer <long char string>","content-length":43}}}`

**Comment by lydonb** [comment]
@dlively1, @adtennant, @robertpeacock22 - I was able to fix this issue by changing my API version from "34" to "34.0". It looks like that setting is used as part of the Salesforce endpoint URL, and you need the ".0" on the end to get the correct URL.

**Comment by dlively1** [comment]
@lydonb that did the trick, thanks for sharing your fix.

**Comment by grekker** [comment]
Where are you changing the API version? I've changed mine in both the package.xml file and and the package settings screen, but still getting this error when I try to create metadata or save an object file. I also deleted and recreated MavensMate projects in case there's some kind of cache in the config folder.

<img width="854" alt="screenshot 2015-07-09 15 20 56" src="https://cloud.githubusercontent.com/assets/131729/8610488/645de688-264e-11e5-9e93-9756d2dc96d9.png">
<img width="264" alt="screenshot 2015-07-09 15 21 11" src="https://cloud.githubusercontent.com/assets/131729/8610489/6460dfe6-264e-11e5-8324-1e0682acfc52.png">

OS X: 10.10.3
Atom 1.0.2
MavensMate-Atom 0.0.24

**Comment by dlively1** [comment]
@grekker I just updated the package setting screen, just as you did in the first screenshot. The only other thing I can think of I did was restart Atom

**Comment by grekker** [comment]
Thanks for the answer. I originally followed your workaround earlier in the week, I've restarted Atom and the computer itself numerous times since then with no luck (and created new MavensMate projects). My best guess at the moment is something is cached somewhere and I'm missing it. Maybe when I have free time this weekend I'll sit down and reinstall each component from scratch and see if that helps.

In the meantime I've reinstalled good old Sublime/MavensMate, which is working fine. It actually makes me realize how many weird little problems Atom/MavensMate has, like the error that gets thrown if you have an .object file open when a project initializes, or the fact that often when I clean my project all the folders stop expanding and I have to restart Atom.

I'll report back here if I get this working.

**Comment by joeferraro** [comment]
this is a node version issue, 0.10.x works fine, 0.12.x does not. there were several updates to the node stream api in 0.12.x which are likely the culprit.

**Comment by tsett075** [comment]
I have switched my version of node to 0.10.40 and still having this issue. Could you explain how to make sure we are running the correct version of node. Thanks

**Comment by lydonb** [comment]
Here's a temporary fix Joe identified int the jsforce library:
https://github.com/jsforce/jsforce/issues/241

I updated the code on my machine and it worked.
