### ISSUE TITLE
fixing compilation error(s) does not clear errors view

### ISSUE THREAD

**Issue by joeferraro** [joeferraro/MavensMate-Atom#256]

**Comment by ejmunson** [comment]
I'm experiencing the same issue with a fresh install of OSX, Atom, Mavens Mate Desktop, and the MavensMate-Atom plugin. If I purposefully introduce an error in code and save it will fail to compile and I will see the status button with "1 error". However, when I fix the error and save successfully the status button still notifies me of "1 error" and takes me to the "Errors" page where it shows the error that was just fixed. Saving multiple times with successful compiles does not remove the error status.

macOS: 10.12
Atom: 1.10.2
MavensMate-app: 0.0.10 
MavensMate-atom: 1.0.9

Note: I had this same bug with previous versions of OSX (before it was called macOS).

**Comment by mfl5** [comment]
I'm still having this same issue as well

**Comment by JBHipple** [comment]
Also having this issue.

MacOS: 10.12.2
Atom: 1.14.3 x64
MavensMate Desktop: 0.0.11 beta 7
MavensMate Atom: 1.0.10

**Comment by anthony-ng** [comment]
I have the same issue.

MacOS: 10.12.3
Atom: 1.15.0 x64
MavensMate Desktop: 0.0.11 beta 7
MavensMate Atom: 1.0.10

**Comment by venkatpolisetti** [comment]
This is still happening. Just installed latest mavensmate desktop and the error count sill there even after it is successfully compiled saved the next time.

Windows 7 / Windows 10
